import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Expense, Group, Payment } from '@/types';

// ─── Types ──────────────────────────────────────────────────────────────────

interface ExpenseWithGroup extends Expense {
    groupName: string;
}

interface ExportOptions {
    userName: string;
    formatDate: (date: Date) => string;
}

// ─── Download Helper ────────────────────────────────────────────────────────

function downloadBlob(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

function formatCurrency(amount: number): string {
    return `$${amount.toFixed(2)}`;
}

// ─── 1. GROUP-LEVEL EXPORTS ─────────────────────────────────────────────────

export function exportGroupCSV(
    group: Group,
    expenses: Expense[],
    payments: Payment[],
    options: ExportOptions
) {
    const lines: string[] = [];

    // Group Info
    lines.push(`Group Name,${csvSafe(group.name)}`);
    lines.push(`Description,${csvSafe(group.description)}`);
    lines.push(`Members,${group.members.length}`);
    lines.push(`Total Expenses,${formatCurrency(expenses.reduce((s, e) => s + e.amount, 0))}`);
    lines.push('');

    // Members
    lines.push('── Members ──');
    lines.push('Name,Email,Role');
    group.members.forEach((m) => {
        lines.push(`${csvSafe(m.displayName)},${csvSafe(m.email)},${m.role}`);
    });
    lines.push('');

    // Expenses
    lines.push('── Expenses ──');
    lines.push('Date,Description,Amount,Paid By,Category,Split Among,Status');
    expenses.forEach((exp) => {
        const paidStatus = payments.some((p) => p.expenseId === exp.id) ? 'Paid' : 'Pending';
        const splitNames = exp.splitAmong
            .map((uid) => group.members.find((m) => m.uid === uid)?.displayName || uid)
            .join('; ');
        lines.push(
            `${options.formatDate(exp.createdAt)},${csvSafe(exp.description)},${formatCurrency(exp.amount)},${csvSafe(exp.paidByName)},${exp.category || 'Other'},${csvSafe(splitNames)},${paidStatus}`
        );
    });
    lines.push('');

    // Member Contributions
    lines.push('── Individual Contributions ──');
    lines.push('Member,Total Paid,Expenses Count');
    group.members.forEach((m) => {
        const memberExpenses = expenses.filter((e) => e.paidBy === m.uid);
        const totalPaid = memberExpenses.reduce((s, e) => s + e.amount, 0);
        lines.push(`${csvSafe(m.displayName)},${formatCurrency(totalPaid)},${memberExpenses.length}`);
    });

    const csvContent = lines.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    downloadBlob(blob, `FairShare_${sanitize(group.name)}_${dateStamp()}.csv`);
}

export function exportGroupPDF(
    group: Group,
    expenses: Expense[],
    payments: Payment[],
    options: ExportOptions
) {
    const pdf = new jsPDF();
    const totalAmount = expenses.reduce((s, e) => s + e.amount, 0);

    // ── Header ──
    pdf.setFontSize(22);
    pdf.setTextColor(31, 58, 95);
    pdf.text('FairShare', 14, 22);

    pdf.setFontSize(10);
    pdf.setTextColor(46, 139, 139);
    pdf.text(`Group Report: ${group.name}`, 14, 30);

    pdf.setFontSize(9);
    pdf.setTextColor(107, 127, 153);
    pdf.text(`Generated by ${options.userName} on ${options.formatDate(new Date())}`, 14, 37);

    // Divider
    pdf.setDrawColor(227, 234, 244);
    pdf.setLineWidth(0.5);
    pdf.line(14, 41, 196, 41);

    // ── Group Summary ──
    pdf.setFontSize(12);
    pdf.setTextColor(31, 58, 95);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Group Summary', 14, 50);

    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(43, 43, 43);
    pdf.text(`Description: ${group.description || 'N/A'}`, 14, 58);
    pdf.text(`Members: ${group.members.length}`, 14, 64);
    pdf.text(`Total Expenses: ${formatCurrency(totalAmount)}`, 14, 70);
    pdf.text(`Number of Expenses: ${expenses.length}`, 105, 64);

    // ── Members Table ──
    pdf.setFontSize(11);
    pdf.setTextColor(31, 58, 95);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Members', 14, 82);

    const memberRows = group.members.map((m) => {
        const paid = expenses.filter((e) => e.paidBy === m.uid).reduce((s, e) => s + e.amount, 0);
        return [m.displayName, m.email, m.role, formatCurrency(paid)];
    });

    autoTable(pdf, {
        startY: 86,
        head: [['Name', 'Email', 'Role', 'Total Paid']],
        body: memberRows,
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [46, 139, 139], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [247, 249, 251] },
        margin: { left: 14, right: 14 },
    });

    // ── Expenses Table ──
    let yPos = (pdf as any).lastAutoTable?.finalY || 120;
    if (yPos > 240) { pdf.addPage(); yPos = 20; }

    pdf.setFontSize(11);
    pdf.setTextColor(31, 58, 95);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Expenses', 14, yPos + 10);

    const expenseRows = expenses.map((exp) => {
        const paidStatus = payments.some((p) => p.expenseId === exp.id) ? 'Paid' : 'Pending';
        return [
            options.formatDate(exp.createdAt),
            exp.description,
            formatCurrency(exp.amount),
            exp.paidByName,
            exp.category || 'Other',
            paidStatus,
        ];
    });

    autoTable(pdf, {
        startY: yPos + 14,
        head: [['Date', 'Description', 'Amount', 'Paid By', 'Category', 'Status']],
        body: expenseRows,
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [31, 58, 95], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [247, 249, 251] },
        margin: { left: 14, right: 14 },
    });

    // ── Total ──
    const finalY2 = (pdf as any).lastAutoTable?.finalY || 200;
    pdf.setFontSize(12);
    pdf.setTextColor(31, 58, 95);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Total: ${formatCurrency(totalAmount)}`, 14, finalY2 + 12);

    // ── Footer ──
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(157, 174, 197);
    pdf.text(`Generated by FairShare`, 14, pdf.internal.pageSize.height - 10);

    pdf.save(`FairShare_${sanitize(group.name)}_${dateStamp()}.pdf`);
}

// ─── 2. SINGLE EXPENSE EXPORT ───────────────────────────────────────────────

export function exportExpenseCSV(
    expense: Expense,
    group: Group,
    payments: Payment[],
    options: ExportOptions
) {
    const paidStatus = payments.some((p) => p.expenseId === expense.id) ? 'Paid' : 'Pending';
    const splitNames = expense.splitAmong
        .map((uid) => group.members.find((m) => m.uid === uid)?.displayName || uid)
        .join('; ');

    const lines = [
        `Expense Title,${csvSafe(expense.description)}`,
        `Amount,${formatCurrency(expense.amount)}`,
        `Paid By,${csvSafe(expense.paidByName)}`,
        `Category,${expense.category || 'Other'}`,
        `Date,${options.formatDate(expense.createdAt)}`,
        `Group,${csvSafe(group.name)}`,
        `Status,${paidStatus}`,
        `Split Among,${csvSafe(splitNames)}`,
        `Per Person,${formatCurrency(expense.amount / expense.splitAmong.length)}`,
    ];

    if (expense.location?.city) {
        lines.push(`Location,${csvSafe(`${expense.location.city}, ${expense.location.country || ''}`)}`);
    }

    const csvContent = lines.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    downloadBlob(blob, `FairShare_Expense_${sanitize(expense.description)}_${dateStamp()}.csv`);
}

export function exportExpensePDF(
    expense: Expense,
    group: Group,
    payments: Payment[],
    options: ExportOptions
) {
    const pdf = new jsPDF();
    const paidStatus = payments.some((p) => p.expenseId === expense.id) ? 'Paid' : 'Pending';
    const perPerson = expense.amount / expense.splitAmong.length;

    // ── Header ──
    pdf.setFontSize(22);
    pdf.setTextColor(31, 58, 95);
    pdf.text('FairShare', 14, 22);

    pdf.setFontSize(10);
    pdf.setTextColor(46, 139, 139);
    pdf.text('Expense Receipt', 14, 30);

    pdf.setFontSize(9);
    pdf.setTextColor(107, 127, 153);
    pdf.text(`Generated on ${options.formatDate(new Date())}`, 14, 37);

    pdf.setDrawColor(227, 234, 244);
    pdf.setLineWidth(0.5);
    pdf.line(14, 41, 196, 41);

    // ── Expense Details ──
    const details = [
        ['Title', expense.description],
        ['Amount', formatCurrency(expense.amount)],
        ['Paid By', expense.paidByName],
        ['Category', expense.category || 'Other'],
        ['Date', options.formatDate(expense.createdAt)],
        ['Group', group.name],
        ['Status', paidStatus],
        ['Per Person', formatCurrency(perPerson)],
    ];

    if (expense.location?.city) {
        details.push(['Location', `${expense.location.city}, ${expense.location.country || ''}`]);
    }

    autoTable(pdf, {
        startY: 48,
        body: details,
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: {
            0: { fontStyle: 'bold', textColor: [31, 58, 95], cellWidth: 40 },
            1: { textColor: [43, 43, 43] },
        },
        alternateRowStyles: { fillColor: [247, 249, 251] },
        margin: { left: 14, right: 14 },
        theme: 'plain',
    });

    // ── Split Details ──
    let yPos = (pdf as any).lastAutoTable?.finalY || 120;
    pdf.setFontSize(11);
    pdf.setTextColor(31, 58, 95);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Split Details', 14, yPos + 12);

    const splitRows = expense.splitAmong.map((uid) => {
        const member = group.members.find((m) => m.uid === uid);
        const hasPaid = payments.some((p) => p.expenseId === expense.id && p.userId === uid);
        return [member?.displayName || uid, formatCurrency(perPerson), hasPaid ? 'Paid' : 'Pending'];
    });

    autoTable(pdf, {
        startY: yPos + 16,
        head: [['Member', 'Share', 'Status']],
        body: splitRows,
        styles: { fontSize: 9, cellPadding: 4 },
        headStyles: { fillColor: [46, 139, 139], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [247, 249, 251] },
        margin: { left: 14, right: 14 },
    });

    // ── Footer ──
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(157, 174, 197);
    pdf.text(`Generated by FairShare`, 14, pdf.internal.pageSize.height - 10);

    pdf.save(`FairShare_Expense_${sanitize(expense.description)}_${dateStamp()}.pdf`);
}

// ─── 3. DATE-FILTERED REPORT EXPORTS ────────────────────────────────────────

export interface ReportData {
    title: string;
    dateRange: string;
    expenses: ExpenseWithGroup[];
    groups: Group[];
}

export function exportReportCSV(report: ReportData, options: ExportOptions) {
    const lines: string[] = [];
    const totalSpent = report.expenses.reduce((s, e) => s + e.amount, 0);

    lines.push(`Report,${csvSafe(report.title)}`);
    lines.push(`Period,${csvSafe(report.dateRange)}`);
    lines.push(`Generated By,${csvSafe(options.userName)}`);
    lines.push(`Total Spent,${formatCurrency(totalSpent)}`);
    lines.push(`Total Expenses,${report.expenses.length}`);
    lines.push('');

    // Category breakdown
    lines.push('── Category Breakdown ──');
    lines.push('Category,Amount,Count');
    const categoryMap = new Map<string, { amount: number; count: number }>();
    report.expenses.forEach((e) => {
        const cat = e.category || 'Other';
        const existing = categoryMap.get(cat) || { amount: 0, count: 0 };
        categoryMap.set(cat, { amount: existing.amount + e.amount, count: existing.count + 1 });
    });
    categoryMap.forEach((val, key) => {
        lines.push(`${key},${formatCurrency(val.amount)},${val.count}`);
    });
    lines.push('');

    // Group-wise breakdown
    lines.push('── Group-wise Breakdown ──');
    lines.push('Group,Amount,Expenses');
    const groupMap = new Map<string, { name: string; amount: number; count: number }>();
    report.expenses.forEach((e) => {
        const existing = groupMap.get(e.groupId) || { name: e.groupName, amount: 0, count: 0 };
        groupMap.set(e.groupId, { name: e.groupName, amount: existing.amount + e.amount, count: existing.count + 1 });
    });
    groupMap.forEach((val) => {
        lines.push(`${csvSafe(val.name)},${formatCurrency(val.amount)},${val.count}`);
    });
    lines.push('');

    // All Expenses
    lines.push('── Expenses ──');
    lines.push('Date,Description,Amount,Paid By,Group,Category');
    report.expenses.forEach((exp) => {
        lines.push(
            `${options.formatDate(exp.createdAt)},${csvSafe(exp.description)},${formatCurrency(exp.amount)},${csvSafe(exp.paidByName)},${csvSafe(exp.groupName)},${exp.category || 'Other'}`
        );
    });

    const csvContent = lines.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    downloadBlob(blob, `FairShare_${sanitize(report.title)}_${dateStamp()}.csv`);
}

export function exportReportPDF(report: ReportData, options: ExportOptions) {
    const pdf = new jsPDF();
    const totalSpent = report.expenses.reduce((s, e) => s + e.amount, 0);

    // ── Header ──
    pdf.setFontSize(22);
    pdf.setTextColor(31, 58, 95);
    pdf.text('FairShare', 14, 22);

    pdf.setFontSize(12);
    pdf.setTextColor(46, 139, 139);
    pdf.setFont('helvetica', 'bold');
    pdf.text(report.title, 14, 30);

    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(107, 127, 153);
    pdf.text(`Period: ${report.dateRange}`, 14, 37);
    pdf.text(`User: ${options.userName} | Generated: ${options.formatDate(new Date())}`, 14, 43);

    pdf.setDrawColor(227, 234, 244);
    pdf.setLineWidth(0.5);
    pdf.line(14, 47, 196, 47);

    // ── Summary Cards Row ──
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(31, 58, 95);
    pdf.text('Total Spent', 14, 56);
    pdf.setFontSize(16);
    pdf.setTextColor(46, 139, 139);
    pdf.text(formatCurrency(totalSpent), 14, 64);

    pdf.setFontSize(10);
    pdf.setTextColor(31, 58, 95);
    pdf.text('Expenses', 80, 56);
    pdf.setFontSize(16);
    pdf.text(`${report.expenses.length}`, 80, 64);

    const uniqueGroups = new Set(report.expenses.map((e) => e.groupId)).size;
    pdf.setFontSize(10);
    pdf.setTextColor(31, 58, 95);
    pdf.text('Groups', 140, 56);
    pdf.setFontSize(16);
    pdf.text(`${uniqueGroups}`, 140, 64);

    // ── Category Breakdown ──
    pdf.setFontSize(11);
    pdf.setTextColor(31, 58, 95);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Category Breakdown', 14, 78);

    const categoryMap = new Map<string, { amount: number; count: number }>();
    report.expenses.forEach((e) => {
        const cat = e.category || 'Other';
        const existing = categoryMap.get(cat) || { amount: 0, count: 0 };
        categoryMap.set(cat, { amount: existing.amount + e.amount, count: existing.count + 1 });
    });
    const catRows = Array.from(categoryMap.entries())
        .sort((a, b) => b[1].amount - a[1].amount)
        .map(([cat, data]) => [
            cat.charAt(0).toUpperCase() + cat.slice(1),
            formatCurrency(data.amount),
            `${data.count}`,
            `${totalSpent > 0 ? ((data.amount / totalSpent) * 100).toFixed(1) : 0}%`,
        ]);

    autoTable(pdf, {
        startY: 82,
        head: [['Category', 'Amount', 'Count', '% of Total']],
        body: catRows,
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [46, 139, 139], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [247, 249, 251] },
        margin: { left: 14, right: 14 },
    });

    // ── Group-wise Breakdown ──
    let yPos = (pdf as any).lastAutoTable?.finalY || 130;
    if (yPos > 230) { pdf.addPage(); yPos = 20; }

    pdf.setFontSize(11);
    pdf.setTextColor(31, 58, 95);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Group-wise Summary', 14, yPos + 10);

    const groupMap = new Map<string, { name: string; amount: number; count: number }>();
    report.expenses.forEach((e) => {
        const existing = groupMap.get(e.groupId) || { name: e.groupName, amount: 0, count: 0 };
        groupMap.set(e.groupId, { name: e.groupName, amount: existing.amount + e.amount, count: existing.count + 1 });
    });
    const groupRows = Array.from(groupMap.values())
        .sort((a, b) => b.amount - a.amount)
        .map((g) => [g.name, formatCurrency(g.amount), `${g.count}`]);

    autoTable(pdf, {
        startY: yPos + 14,
        head: [['Group', 'Total Amount', 'Expenses']],
        body: groupRows,
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [31, 58, 95], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [247, 249, 251] },
        margin: { left: 14, right: 14 },
    });

    // ── All Expenses ──
    let yPos2 = (pdf as any).lastAutoTable?.finalY || 180;
    if (yPos2 > 230) { pdf.addPage(); yPos2 = 20; }

    pdf.setFontSize(11);
    pdf.setTextColor(31, 58, 95);
    pdf.setFont('helvetica', 'bold');
    pdf.text('All Expenses', 14, yPos2 + 10);

    const expenseRows = report.expenses.map((exp) => [
        options.formatDate(exp.createdAt),
        exp.description.length > 25 ? exp.description.substring(0, 25) + '...' : exp.description,
        formatCurrency(exp.amount),
        exp.paidByName,
        exp.groupName,
    ]);

    autoTable(pdf, {
        startY: yPos2 + 14,
        head: [['Date', 'Description', 'Amount', 'Paid By', 'Group']],
        body: expenseRows,
        styles: { fontSize: 7, cellPadding: 3 },
        headStyles: { fillColor: [31, 58, 95], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [247, 249, 251] },
        margin: { left: 14, right: 14 },
    });

    // ── Footer ──
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(157, 174, 197);
        pdf.text(`FairShare | Page ${i} of ${totalPages}`, 14, pdf.internal.pageSize.height - 10);
    }

    pdf.save(`FairShare_${sanitize(report.title)}_${dateStamp()}.pdf`);
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function csvSafe(str: string): string {
    if (!str) return '';
    return `"${str.replace(/"/g, '""')}"`;
}

function sanitize(str: string): string {
    return str.replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 30);
}

function dateStamp(): string {
    return new Date().toISOString().slice(0, 10);
}
